development:
  adapter: postgresql
  encoding: unicode
  database: photo_gallery_development
  pool: 5
  username: marc
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: photo_gallery_test
  pool: 5
  username: marc
  password:
cucumber:
  <<: *test